### ISSUE TITLE
Publish package to PyPI

### ISSUE THREAD

**Issue by justinmayer** [pelican-plugins/injector#4]
Hey @buanzo. Nice work on the follow-up changes to the Injector plugin. Following are some things I noticed upon returning to my desk and reviewing the recent developments:

- #1 was merged before it was fully ready. When you see commits prefixed by `fixup! […]`, those are intended to be squashed into their parent commits before the PR is merged. So what I was looking for in that case was a PR review and approval, after which I would have squashed the commits and merged the PR. Not a big deal, of course. Just something to keep in mind for the future in order to keep commit history somewhat organized and tidy.
- There is (another) copy+paste fail in the badge links in the README.
- The contents of #1 were manually tagged with `1.0.0` and a GitHub release was added manually, whereas these steps are usually handled automatically in CI via [AutoPub](https://justinmayer.com/projects/autopub/) and GitHub Actions.

Regarding fixing the latter two issues, I'd like to do the following:

- Fix the README badge links.
- Remove the `1.0.0` tag and GitHub release.
- Use AutoPub to publish the contents of current `main` as `1.0.0` on GitHub and PyPI.

Any objections if I go ahead and take these remedial actions?

**Comment by buanzo** [comment]
I appreciate your explanation and kindness. No objections. Thank you again.

**Comment by justinmayer** [comment]
My pleasure, Arturo. I made the above-mentioned changes and utilized the existing auto-publish infrastructure to re-tag and [release 1.0.0 to GitHub](https://github.com/pelican-plugins/injector/releases/tag/1.0.0) and PyPI. 🎊 

It's been a pleasure to collaborate with you. I look forward to further enhancements to the plugin as well as to your continued participation in the greater Pelican community. 🌟

**Comment by buanzo** [comment]
I am already working on some ideas  learning a lot! I like publishing
packages manually, but your auto pub looks amazing. Will use it! Thank you
and the community for this amazing Pelican ;)

Gracias!
